name: ravuprompt build
on: [push]
jobs:
  build-debug:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    env:
      RUST_BACKTRACE: 1
    permissions:
      contents: write
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm git rustup
      - name: install rust
        run: rustup toolchain install stable
      - name: check out repository code
        uses: actions/checkout@v7
      - name: run build
        run: cargo build
      - name: run tests
        run: cargo test
      - name: upload binary
        uses: actions/upload-artifact@v7
        with:
          name: ravuprompt-debug
          path: |
            zshrc
            target/debug/ravuprompt
      - name: gift-wrap release
        run: tar -czf ravuprompt-linux-debug-x86_64-${{ github.ref_name }}.tar.gz zshrc -C target/debug/ ravuprompt
        if: github.ref_type == 'tag'
      - name: release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            ravuprompt-linux-debug-x86_64-${{ github.ref_name }}.tar.gz
  build-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    env:
      RUST_BACKTRACE: 1
    permissions:
      contents: write
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm git rustup
      - name: install rust
        run: rustup toolchain install stable
      - name: check out repository code
        uses: actions/checkout@v7
      - name: run build
        run: cargo build --release
      - name: run tests
        run: cargo test --release
      - name: upload binary
        uses: actions/upload-artifact@v7
        with:
          name: ravuprompt-release
          path: |
            zshrc
            target/release/ravuprompt
      - name: gift-wrap release
        run: tar -czf ravuprompt-linux-release-x86_64-${{ github.ref_name }}.tar.gz zshrc -C target/release/ ravuprompt
        if: github.ref_type == 'tag'
      - name: release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            ravuprompt-linux-release-x86_64-${{ github.ref_name }}.tar.gz
  build-release-musl:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    env:
      RUST_BACKTRACE: 1
    permissions:
      contents: write
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm git rustup
      - name: install rust
        run: rustup toolchain install stable --target=x86_64-unknown-linux-musl
      - name: check out repository code
        uses: actions/checkout@v7
      - name: run build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: upload binary
        uses: actions/upload-artifact@v7
        with:
          name: ravuprompt-release-musl
          path: |
            zshrc
            target/x86_64-unknown-linux-musl/release/ravuprompt
      - name: gift-wrap release
        run: tar -czf ravuprompt-linuxmusl-release-x86_64-${{ github.ref_name }}.tar.gz zshrc -C target/x86_64-unknown-linux-musl/release/ ravuprompt
        if: github.ref_type == 'tag'
      - name: release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            ravuprompt-linuxmusl-release-x86_64-${{ github.ref_name }}.tar.gz
